services:
  github:
    tool:
      name: github_onboarding_tool
      description: |- 
        "Onboarding to GitHub based on information in form of yaml."
    instruction: |-
      "Before we can onboard you to GitHub, we need some information from you. Please see the checklist below:"
  
  launchdarkly:
    tool:
      name: launchdarkly_onboarding_tool
      description: |- 
        "Onboarding to LaunchDarkly based on information."
    instruction: |-
        "Before we can onboard you to LaunchDarkly, we need some information from you. Please see the checklist below:"
  snyk:
    tool:
      name: snyk_onboarding_tool
      description: |- 
        "Onboarding to Snyk based on information."
    instruction: |-
        "Before we can onboard you to Snyk, we need some information from you. Please see the checklist below:"
    
    